version: '3.3'
services:

  glances:
    image: nicolargo/glances:latest-full
    restart: always
    pid: host
    mem_limit: 100M
    memswap_limit: 256M
    environment:
      - 'TZ=Asia/Shanghai'
      - 'GLANCES_OPT=-C /etc/glances.conf -w'
    ports:
      - '61208-61209:61208-61209'
    volumes:
      - './glances.conf:/etc/glances.conf'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    container_name: glances